
# Links: 
# https://github.com/itzg/docker-minecraft-server
# https://help.github.com/en/actions/configuring-and-managing-workflows/about-service-containers
# https://help.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices
# https://github.com/itzg/mc-monitor
# https://github.com/actions/example-services/blob/master/.github/workflows/redis-service.yml
# https://stackoverflow.com/questions/57549439/how-do-i-use-docker-with-github-actions

on: [push]

jobs:
  download_mod:
    name: Download mod
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        id: pwd_path
        run: pwd
        shell: bash
    
      - name: Display current directory
        id: ls_path
        run: ls -la
        shell: bash

      - name: Create mods dir
        id: mkdir_data
        run: mkdir /mods

      - name: CD to mods dir
        id: cd_mods
        run: cd /mods

      - name: Download mod
        id: download_mod
        run: wget https://github.com/athrane/bassebombecraft/releases/download/1.42.1/BasseBombeCraft-1.15.2-1.42-server.jar

      - name: Display the mod directory
        id: ls_mod_dir
        run: ls -la /mods
        shell: bash

  test_mod:
    name: Test mod in server 
    needs: download_mod
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      mcserver:
        image: itzg/minecraft-server:multiarch      
        env:
          NAME: mc
          EULA: TRUE
          VERSION: 1.15.2
          TYPE: FORGE
          FORGEVERSION: 31.1.10
        ports:
          - 25565:25565
        volumes:
           - /mods:/mods
        options: --name minecraftserver

    steps:
      - name: Display the mod directory
        id: ls_mod_dir
        run: ls -la /mods
        shell: bash
    
      - name: Get Minecraft container health
        id: mc_container_health
        run: /usr/bin/docker container inspect -f "{{.State.Health.Status}}" minecraftserver

      - name: Display Minecraft container logs
        id: mc_container_logs
        run: /usr/bin/docker logs minecraftserver
        