
# Links: 
# https://github.com/itzg/docker-minecraft-server
# https://help.github.com/en/actions/configuring-and-managing-workflows/about-service-containers
# https://help.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices
# https://github.com/itzg/mc-monitor
# https://github.com/actions/example-services/blob/master/.github/workflows/redis-service.yml
# https://stackoverflow.com/questions/57549439/how-do-i-use-docker-with-github-actions

# https://dev.to/s_abderemane/how-to-use-docker-services-in-github-actions-6ce
# https://github.com/peter-evans/docker-compose-actions-workflow
# https://github.community/t5/GitHub-Actions/Github-Actions-services-not-reachable/td-p/30050
# https://docs.docker.com/engine/reference/commandline/create/#options
# https://github.com/itzg/docker-minecraft-server/blob/master/examples/docker-compose-forge.yml
# https://docs.docker.com/compose/compose-file/
# https://ryaneschinger.com/blog/using-docker-native-health-checks/
# https://github.com/laradock/laradock/blob/master/docker-compose.yml
# https://testdriven.io/blog/deploying-django-to-digitalocean-with-docker-and-github-actions/
# https://github.com/peter-evans/docker-compose-healthcheck
# https://ryaneschinger.com/blog/using-docker-native-health-checks/
# https://www.datanovia.com/en/courses/docker-compose-wait-for-dependencies/

# https://project-awesome.org/sdras/awesome-actions#collection-of-actions
# https://github.com/jakejarvis/wait-action
# https://github.com/Eficode/wait-for
# https://github.com/vishnubob/wait-for-it
# https://docs.docker.com/compose/startup-order/
# https://hub.docker.com/r/itzg/minecraft-server/dockerfile/

on: [push]

jobs:
  download_mod:
    name: Download mod
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        id: checkout_source
        uses: actions/checkout@v2

      - name: Display the path
        id: pwd_path
        run: pwd

      - name: Show processes and ports
        id: show_ports
        run: netstat -tulpn

      - name: Display current directory
        id: ls_path
        run: ls -la

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag athrane/minecraft:1 --tag athrane/minecraft:latest

  test_mod:
    name: Test mod in server 
    needs: download_mod
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      mcserver:
        image: athrane/minecraft:latest
        ports:
          - 25565:25565
        options: --name minecraftserver

    steps:    
      - name: Get Minecraft container health
        id: mc_container_health
        run: /usr/bin/docker container inspect -f "{{.State.Health.Status}}" minecraftserver

      - name: Display Minecraft container logs
        id: mc_container_logs
        run: /usr/bin/docker logs minecraftserver

      - name: Display the mod directory
        id: ls_mod_dir
        run: ls -la $GITHUB_WORKSPACE/mods
        shell: bash

