
# Links: 
# https://github.com/itzg/docker-minecraft-server
# https://help.github.com/en/actions/configuring-and-managing-workflows/about-service-containers
# https://help.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices
#https://github.com/itzg/mc-monitor

on: [push]

jobs:
  test_minecraft-mod-job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    container: node:10.18-jessie
    services:
    
      # Label used to access the service container
      mcserver:
        image: itzg/minecraft-server:multiarch
      
        # Set environment variables
        env:
          NAME: mc
          EULA: TRUE

        # Map port 25565 on the Docker host to port 25565 on the mc container
        ports:
          - 25565:25565

    steps:
      - name: Display the path
        id: ls_path
        run: ls -la
        shell: bash